version: 2.1

orbs:
  node: circleci/node@5
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: 
        name: Run tetss
        command: npm test

  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test